openapi: 3.0.0
x-stoplight:
  id: cfbbd33a0bd5a
info:
  title: Organization
  version: '1.0'
  description: ''
servers:
  - url: 'https://api.commoncents.io/organization'
paths: {}
components:
  schemas:
    Entity:
      title: Entity
      x-stoplight:
        id: z4gv4qa6da7oi
      type: object
      properties:
        id:
          type: string
    User:
      title: User
      x-stoplight:
        id: t0i5luq098rj7
      type: object
      properties:
        id:
          type: string
