openapi: 3.0.0
info:
  title: Notify
  version: '1.0'
  description: testing
servers:
  - url: 'http://localhost:3000'
paths:
  /sms:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-sms
    post:
      summary: ''
      operationId: post-sms
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                ToEmail:
                  type: string
                '':
                  type: string
  /conversation:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-conversation
      description: Get a list of conversations
    post:
      summary: Create a conversation
      operationId: post-conversation
      responses:
        '200':
          description: OK
      description: in order to create a group conversation you have to initiate a group conversation
  /email:
    post:
      summary: ''
      operationId: post-email
      responses:
        '200':
          description: OK
components:
  schemas:
    Message:
      title: Message
      type: object
      properties:
        id:
          type: string
    Converstation:
      title: Converstation
      type: object
      properties:
        id:
          type: string
